name: Monitor Ransomware Feed

on:
  schedule:
    - cron: '*/5 * * * *' # Gira ogni 30 minuti
  workflow_dispatch: # Questo ti permette di farlo partire a mano per testare

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout codice
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Installa librerie
        run: pip install feedparser requests

      - name: Esegui lo script
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python rss_1.py

      - name: Salva cronologia
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add history.txt || true
          git commit -m "Update news history" || exit 0
          git push
